# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fcb93cb890054489684cc0d461850ee7d7fbb186b267862ced450701af989d13683c0e1055f88326ea5a9037a37c6097bcb14e194c3ba6d2a7b7290bf29b8d8

test:
  secret_key_base: d6eed65e5c7952e4aa26035eaf6e7a8eb7f128e47a38885ad5ac084ff8d99e216ba7c23b11c59f32ea2e738be3f4f8f8c8e57733f1e1e7edb9c2a8d867ed51fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
